language: generic
sudo: required  
services:
  - docker      

before_install: 
  - docker build -t antonio94c/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true antonio94c/docker-react npm run test -- --coverage